### ISSUE TITLE
Missing Dependency?

### ISSUE THREAD

**Issue by msurato** [EncoreTechnologies/puppet-patching#18]
I am working with the plans and have run into a minor issue. At least a couple of the plans (check_online and check_puppet) appear to run the task "puppet_agent::version" which I do not seem to have. Is this the task from the puppet_agent module (https://forge.puppet.com/puppetlabs/puppet_agent/tasks)? If so, the metadata does not have this module as a dependency and I am thus unsure.

Thanks for any insight!

**Comment by nmaludy** [comment]
On my open-source version of Bolt (default install) the `puppet_agent` module is baked in.

```
$ bolt task show
aws_inventory::resolve_reference     Generate targets from AWS EC2 instances
azure_inventory::resolve_reference   Generate targets from Azure VMs
facts                                Gather system facts
package                              Manage and inspect the state of packages
puppet_agent::install                Install the Puppet agent package
puppet_agent::version                Get the version of the Puppet agent package installed. Returns nothing if none present.
puppet_conf                          Inspect puppet agent configuration settings                                                   
reboot                               Reboots a machine                                                                             
reboot::last_boot_time               Gets the last boot time of a Linux or Windows system                                          
service                              Manage and inspect the state of services                                                      
terraform::apply                     Apply an HCL manifest                                                                         
terraform::destroy                   Destroy resources managed with Terraform                                                      
terraform::output                    JSON representation of Terraform outputs                                                      
terraform::resolve_reference         Generate targets from Terraform Statefile                                                     
vault::resolve_reference             Set config values by accessing secrets in Hashicorp Vault                                     
yaml::resolve_reference              Read YAML data from a file                                                                                                                                 
```

```
$ bolt --version
1.43.0
```

**Comment by msurato** [comment]
The default Puppetfile does include this module (https://github.com/puppetlabs/bolt/blob/master/Puppetfile). I am wondering if this should be included as a dependency for this module as well.

**Comment by nmaludy** [comment]
It is there: https://github.com/puppetlabs/bolt/blob/master/Puppetfile#L10

**Comment by msurato** [comment]
True. What I am attempting to do is to use the module directly as a plan in Puppet Enterprise. This is possible with PE 2019.2 (https://puppet.com/docs/pe/2019.2/running_plans_in_pe.html) and thus I am thinking that the dependency should be called out in the metadata for this module as not everyone will be using Bolt in the future.

**Comment by nmaludy** [comment]
Gotcha, based on input i got in Slack. It sounds like `puppet_agent` isn't included in the PE release for some reason. Looks like we just need to add `puppet_agent` to `metadata.json`

**Comment by msurato** [comment]
Awesome! Thanks for looking into it!
