### ISSUE TITLE
Using /etc/os-release

### ISSUE THREAD

**Issue by msurato** [EncoreTechnologies/puppet-patching#2]
I am curious if there is a rationale to using lsb_release and /etc/redhat-release instead of parsing /etc/os-release for the distribution differentiation script. According to http://0pointer.de/blog/projects/os-release os-release is a standard part of systemd which has been the standard on most Linux distributions for a little while now. 

The reason I am asking is that I would like to use this module with SUSE and the branching statements would be simpler for the third distribution with a single case statement against a single variable instead of multiple if statements against multiple variables.

**Comment by nmaludy** [comment]
No real reason, feel free to make a PR if you'd like to improve it.

**Comment by msurato** [comment]
Thanks for the information! I will do that.

**Comment by nmaludy** [comment]
@msurato I think I remember why I went with /etc/redhat-release parsing... RHEL 6 isn't systemd.

Maybe we could look at parsing /etc/os-release if it exists, then fall back to the others if it doesn't.

The other thought I had was to check if `facter` exists and use that as a primary. I hate reinventing the wheel. However, many of our clients that we patch do not have Puppet so I can't rely on Puppet agent and Facter in all cases.

Thoughts?
