### ISSUE TITLE
file::write not supported in PE

### ISSUE THREAD

**Issue by sirinek** [EncoreTechnologies/puppet-patching#29]
When trying to run the plans from the PE console, I get an error because File::Write isnt supported. It works from the command line though.

**Comment by nmaludy** [comment]
Sirinek,

First off, thanks for testing this against PE! I don't have a PE environment, so i really appreciate the feedback. My goal here is to get this working in PE as well, have a couple of questions around that:

- The idea of the `file::write()` is that we want to collect all of the results and write them out locally for an operator to go through (maybe send them to security team, etc).
- Thinking about the PE context, do you want to use these results? If yes, where would you like them sent so you can consume them? Filesystem (which one), a database, something else?

**Comment by sirinek** [comment]
In plans/init.pp, I hardcoded the format argument to patching::update_history to be  "none" to get around this issue. Also, it gets around the below code which is necessary, because I can't set $report_file, it is not passed in the call to patching::update_history and has a hardcoded default in that plan.
```
  if $report_file {
    file::write($report_file, $report)
  }
```

My suggestions for getting around this bug would be to allow the user to set the format type and report_file name (including setting to false or a blank string or some other false-ish thing that's not `undef`... not sure if you can pass undef as a value in the PE orchestrator.)

When I set the format to `"none"` the entire patching plan worked from the PE Console!
