### ISSUE TITLE
When I run bolt plan run -t windows patching::pre_update. The plan executes the script on target windows nodes successfully but the output says it failed.

### ISSUE THREAD

**Issue by SurajNikam1994** [EncoreTechnologies/puppet-patching#42]
I have created a PS script that restarts the windows update service and stored it in C:\ProgramData\patching\bin as specified in the docucmentation. Whenever I run below command, it executes the script sucessfully but returns as failed task. 

[root@csu-tst-pup-p01 ~]# bolt plan run -t windows patching::pre_update
Starting: plan patching::pre_update
Starting: plan patching::get_targets
Starting: plan patching::check_puppet
Starting: task puppet_agent::version on csu-tst-tom-p01, csu-tst-oas-p01
Finished: task puppet_agent::version with 0 failures in 1.52 sec
Starting: plan patching::puppet_facts
Starting: task patching::puppet_facts on csu-tst-tom-p01, csu-tst-oas-p01
Finished: task patching::puppet_facts with 0 failures in 5.85 sec
Finished: plan patching::puppet_facts in 5.87 sec
Finished: plan patching::check_puppet in 7.42 sec
Finished: plan patching::get_targets in 7.43 sec
Starting: plan patching::pre_post_update
pre_post_update - noop = false
Starting: plan patching::get_targets
Finished: plan patching::get_targets in 0.0 sec
Starting: task patching::pre_update on csu-tst-tom-p01, csu-tst-oas-p01
Finished: task patching::pre_update with 2 failures in 3.01 sec
Finished: plan patching::pre_post_update in 3.03 sec
Finished: plan patching::pre_update in 10.47 sec
Failed on testserver2:
  The task failed with exit code 1
  Found Service: wuauserv
  Stopped service: wuauserv
  Started service: wuauserv
Failed on testserver1:
  The task failed with exit code 1
  Found Service: wuauserv
  Stopped service: wuauserv
  Started service: wuauserv
Failed on 2 targets: testserver2,testserver1
Ran on 2 targets

Below is the PS script.

[CmdletBinding()]
param (
  # Name or list of service names to stop
  [Parameter(Mandatory=$false)]
  [string[]]
  $service='wuauserv',
  # Restart the service immediately
  [Parameter(Mandatory=$false)]
  [switch]
  $norestart
)

foreach ($name in $service) {
  try{
    $serviceObject = Get-service -Name $name
    Write-output "Found Service: $name"

    if(-not $serviceObject){
      Write-Output "Service not found: $name"
      continue
    }

    Stop-Service -InputObject $serviceObject -ErrorAction Stop

    Write-Output "Stopped service: $name"

    if($norestart){continue}

    Start-Service -InputObject $serviceObject

    Write-Output "Started service: $name"

  } catch {
    Write-Output "Cannot stop service: $name"
    Write-Output "Dependent services: $($serviceObject.dependentservices)"

    exit 1
  }
}

**Comment by nmaludy** [comment]
@SurajNikam1994 can you please fix the formatting in your example script so i can test?

Thanks!

**Comment by SurajNikam1994** [comment]
Thanks... I changed the script entirely and now it is working. Only thing that I needed to do put a sleep command at the end of Pwsh script.
