### ISSUE TITLE
Feature request: Support puppetlabs/puppet_agent > 3.0

### ISSUE THREAD

**Issue by fetzerms** [EncoreTechnologies/puppet-patching#76]
The current version of puppetlabs/puppet_agent is at 4.4.0. Is there a specific reason, why the version requirement is fixed to <3.0 in metadata.json?

**Comment by nmaludy** [comment]
No reason, would you mind submitting a PR to bump it to <5.0?

**Comment by fetzerms** [comment]
Thanks for merging! Sorry that I did not see the tests. Will be the new Version released to forge soon?

Closing this issue, as it works now.
